# Output a pdf
$pdf_mode = 4;
#$pdflatex = 'pdflatex --shell-escape %O %S';
$lualatex = '(cd img  && latexmk -pdflatex) && lualatex --file-line-error %O %S';

# By default compile only the file called 'main.tex'
@default_files = ('libro-linguaggi.tex');

#clean files generated by custom dependencies
$cleanup_includes_cusdep_generated = 1;
#clean files generated by latex
$cleanup_includes_generated = 1;
#use recorder feature to list input files
$recorder = 1;

# Compile the glossary and acronyms list (package 'glossaries')
add_cus_dep( 'acn', 'acr', 0, 'makeglossaries' );
add_cus_dep( 'glo', 'gls', 0, 'makeglossaries' );

sub makeglossaries {
   my ($base_name, $path) = fileparse( $_[0] );
   pushd $path;
   my $return = system "makeglossaries", $base_name;
   popd;
   return $return;
}

# Compile the nomenclature (package 'nomencl')
add_cus_dep( 'nlo', 'nls', 0, 'makenlo2nls' );
sub makenlo2nls {
    system( "makeindex -s nomencl.ist -o \"$_[0].nls\" \"$_[0].nlo\"" );
}

$pdflatex = 'pdflatex --shell-escape -interaction=batchmode -synctex=1 %O %S';
$latex = 'latex --shell-escape -interaction=batchmode -synctex=1 %O %S';

$clean_ext .= " acr acn alg glo gls glg" .
  "deriv equ glo gls gsprogs hd listing lol" .
  " _minted-%R/* _minted-%R nav snm synctex.gz tcbtemp vpprogs";
#add synctex extensions so they are cleaned
push @generated_exts, 'synctex', 'synctex.gz';



#add generated extensions so they are cleaned correctly
push @generated_exts, 'glo', 'gls', 'glg';
push @generated_exts, 'acn', 'acr', 'alg';
$clean_ext .= ' %R.ist %R.xdy';


add_cus_dep('fig', 'pdf', 0, 'fig2pdf');
sub fig2pdf {
    return system("fig2dev -L pdf \"$_[0].fig\" \"$_[0].pdf\"");
}

add_cus_dep('svg', 'pdf_tex', 0, 'svg2pdf_tex');
sub svg2pdf_tex {
        return system("inkscape --export-area-drawing --export-latex --export-pdf=\"$_[0].pdf\" \"$_[0].svg\"");
}
