TARGETS = libro-linguaggi.pdf
DEPS_DIR = img/
LATEXMK = latexmk -recorder -use-make -deps \
	  -e 'warn qq(In Makefile, turn off custom dependencies\n);' \
	  -e '@cus_dep_list = ();' \
	  -e 'show_cus_dep();'
all : $(TARGETS)
$(foreach file,$(TARGETS),$(eval -include $(DEPS_DIR)/$(file)P))
%.pdf : %.tex
	   $(LATEXMK) -pdf $<
